name: Waka Readme Update

on:
  # Trigger manually or run daily at 12:00 AM UTC
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-24.04

    steps:
      - name: Fetch and Update WakaTime Metrics
        uses: athul/waka-readme@master
        with:
          # Authentication (Required)
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # Meta Tweaks
          API_BASE_URL: https://wakatime.com/api # Default WakaTime API
          REPOSITORY: tidjee-dev/tidjee-dev # Replace with your GitHub repository

          # Content Tweaks
          SHOW_TITLE: true # Show title above stats blob
          SECTION_NAME: waka # Target section name in the README
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿ # Ascii art for graphs (can be customized)
          CODE_LANG: text # Highlight stats as plain text
          TIME_RANGE: last_7_days # Aggregation period (last 7 days)
          LANG_COUNT: 10 # Number of languages to display
          SHOW_TIME: true # Show time spent per language
          SHOW_TOTAL: true # Show total time spent on coding
          SHOW_MASKED_TIME: true # Include masked stats (unclassified time)
          STOP_AT_OTHER: true # Stop after the "Other" language category
          IGNORED_LANGUAGES: Binary # Languages to exclude from stats

          # Commit Tweaks
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics" # Custom commit message
          TARGET_BRANCH: main # Branch to push changes
          TARGET_PATH: README.md # Path of the target file to update
          COMMITTER_NAME: GitHubActionBot # Committer name for the updates
          COMMITTER_EMAIL: action-bot@github.com # Committer email
          AUTHOR_NAME: "Donatien Pinet (tidjee-dev)" # Author name for the updates
          AUTHOR_EMAIL: pinet.donatien@gmail.com # Author email
